/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as InviteTokenRouteImport } from './routes/invite/$token'
import { Route as AuthMagicRouteImport } from './routes/auth/magic'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiInstagramValidateRouteImport } from './routes/api/instagram/validate'
import { Route as ApiInstagramTranscribeRouteImport } from './routes/api/instagram/transcribe'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthMagicRoute = AuthMagicRouteImport.update({
  id: '/auth/magic',
  path: '/auth/magic',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramValidateRoute = ApiInstagramValidateRouteImport.update({
  id: '/api/instagram/validate',
  path: '/api/instagram/validate',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInstagramTranscribeRoute = ApiInstagramTranscribeRouteImport.update({
  id: '/api/instagram/transcribe',
  path: '/api/instagram/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/magic': typeof AuthMagicRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/instagram/transcribe': typeof ApiInstagramTranscribeRoute
  '/api/instagram/validate': typeof ApiInstagramValidateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/magic': typeof AuthMagicRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin': typeof AdminIndexRoute
  '/api/instagram/transcribe': typeof ApiInstagramTranscribeRoute
  '/api/instagram/validate': typeof ApiInstagramValidateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/auth/magic': typeof AuthMagicRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/': typeof AdminIndexRoute
  '/api/instagram/transcribe': typeof ApiInstagramTranscribeRoute
  '/api/instagram/validate': typeof ApiInstagramValidateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/transcribe'
    | '/auth/magic'
    | '/invite/$token'
    | '/admin/'
    | '/api/instagram/transcribe'
    | '/api/instagram/validate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/transcribe'
    | '/auth/magic'
    | '/invite/$token'
    | '/admin'
    | '/api/instagram/transcribe'
    | '/api/instagram/validate'
  id:
    | '__root__'
    | '/'
    | '/api/transcribe'
    | '/auth/magic'
    | '/invite/$token'
    | '/admin/'
    | '/api/instagram/transcribe'
    | '/api/instagram/validate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  AuthMagicRoute: typeof AuthMagicRoute
  InviteTokenRoute: typeof InviteTokenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ApiInstagramTranscribeRoute: typeof ApiInstagramTranscribeRoute
  ApiInstagramValidateRoute: typeof ApiInstagramValidateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/magic': {
      id: '/auth/magic'
      path: '/auth/magic'
      fullPath: '/auth/magic'
      preLoaderRoute: typeof AuthMagicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/validate': {
      id: '/api/instagram/validate'
      path: '/api/instagram/validate'
      fullPath: '/api/instagram/validate'
      preLoaderRoute: typeof ApiInstagramValidateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/instagram/transcribe': {
      id: '/api/instagram/transcribe'
      path: '/api/instagram/transcribe'
      fullPath: '/api/instagram/transcribe'
      preLoaderRoute: typeof ApiInstagramTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  AuthMagicRoute: AuthMagicRoute,
  InviteTokenRoute: InviteTokenRoute,
  AdminIndexRoute: AdminIndexRoute,
  ApiInstagramTranscribeRoute: ApiInstagramTranscribeRoute,
  ApiInstagramValidateRoute: ApiInstagramValidateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
